#

#

name: postgis

services:
  postgis:
    image: postgis/postgis:17-3.5-alpine
    container_name: postgis
    volumes:
      - ./data/:/var/lib/postgresql/data
      - ./shared/:/var/shared
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: changeme
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 15432:5432

networks:
  proxy:
    external: true
