# https://github.com/eitchtee/WYGIWYH

#

name: wygiwyh

services:
  web:
    image: eitchtee/wygiwyh:latest
    container_name: ${SERVER_NAME}
    command: /start
    ports:
      - "${OUTBOUND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - proxy

  db:
    image: postgres:15
    container_name: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    networks:
      - proxy

  procrastinate:
    image: eitchtee/wygiwyh:latest
    container_name: ${PROCRASTINATE_NAME}
    depends_on:
      - db
    env_file:
      - .env
    command: /start-procrastinate
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
