# https://getwud.github.io/wud/#/

#

name: wud

services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    networks:
      - proxy

networks:
  proxy:
    external: true
