# https://github.com/glanceapp/glance

# https://github.com/glanceapp/docker-compose-template/blob/main/root/docker-compose.yml

name: glance

services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    networks:
      - proxy

networks:
  proxy:
    external: true
